name: therapy_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.11
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  pin_code_fields: ^8.0.1
  bloc: ^8.1.4
  device_preview: ^1.1.0
  sqflite: ^2.3.2
  path: ^1.8.3
  image_picker: ^0.8.4+3
  sqflite_common_ffi: ^2.0.0+4
  url_launcher: ^6.2.6
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  firebase_messaging: ^14.9.2
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  awesome_dialog: ^3.2.1
  provider: ^6.1.1

flutter_native_splash:
  background_image: "assets/images/SplashScreen.jpg"
  image: "assets/images/SplashScreen.jpg"

flutter_launcher_icons:
  ios: true
  android: true
  image_path_android: "assets/images/playstore.png"
  image_path_ios: "assets/images/appstore.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/SplashScreen.jpg
    - assets/images/loginbg.jpg
    - assets/images/forget.jpeg
    - assets/images/signup.jpg
    - assets/images/01.jpeg
    - assets/images/02.jpeg
    - assets/images/03.jpeg
    - assets/images/nWork.jpg
    - assets/images/Th1.jpg
    - assets/images/google.png
    - assets/images/theme.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
