// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzV-3_FvB-Ei99kbDvWnu4KUGMHGaLLWw',
    appId: '1:164224139983:web:737399373f2cdfa9f12dba',
    messagingSenderId: '164224139983',
    projectId: 'theranest-8d58e',
    authDomain: 'theranest-8d58e.firebaseapp.com',
    storageBucket: 'theranest-8d58e.appspot.com',
    measurementId: 'G-FF3N3DD0Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXFGe03vRbAVjJ8smDxLsIehO9y8nRJGs',
    appId: '1:164224139983:android:ed3a902b68eae7b2f12dba',
    messagingSenderId: '164224139983',
    projectId: 'theranest-8d58e',
    storageBucket: 'theranest-8d58e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBIypXHiAqBK892tvXVortjbtPeL7NznE',
    appId: '1:164224139983:ios:28588a9b2776b32bf12dba',
    messagingSenderId: '164224139983',
    projectId: 'theranest-8d58e',
    storageBucket: 'theranest-8d58e.appspot.com',
    iosBundleId: 'com.example.therapyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBIypXHiAqBK892tvXVortjbtPeL7NznE',
    appId: '1:164224139983:ios:28588a9b2776b32bf12dba',
    messagingSenderId: '164224139983',
    projectId: 'theranest-8d58e',
    storageBucket: 'theranest-8d58e.appspot.com',
    iosBundleId: 'com.example.therapyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzV-3_FvB-Ei99kbDvWnu4KUGMHGaLLWw',
    appId: '1:164224139983:web:40c2a305151e25f8f12dba',
    messagingSenderId: '164224139983',
    projectId: 'theranest-8d58e',
    authDomain: 'theranest-8d58e.firebaseapp.com',
    storageBucket: 'theranest-8d58e.appspot.com',
    measurementId: 'G-QX6T3PDDEL',
  );
}
